### ISSUE TITLE
Argument error when using rest-client-1.8.0

### ISSUE THREAD

**Issue by darrenleeweber** [crohr/rest-client-components#8]
While using RDF.rb with rest-client-1.8.0 and rest-client-components-1.3.0

```
[1] pry(main)> g = RDF::Graph.load('http://id.loc.gov/authorities/names/no99010609.rdf')
ArgumentError: wrong number of arguments (3 for 4)
from /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/response.rb:13:in `create'
[2] pry(main)> wtf
Exception: ArgumentError: wrong number of arguments (3 for 4)
--
0: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/response.rb:13:in `create'
1: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-components-1.3.0/lib/restclient/components.rb:16:in `call'
2: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-components-1.3.0/lib/restclient/components.rb:136:in `execute'
3: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
4: /home/dlweber/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
```

**Comment by gkellogg** [comment]
Just to clarify, when requiring restclient/components, the following code provokes the issue:

    client = RestClient::Resource.new(base_uri, verify_ssl: ssl_verify)
    client.get(headers) do |response, request, res, &blk|
      ...

**Comment by gkellogg** [comment]
Relevant gems and versions from Gemfile:

  * addressable (2.3.8)
  * builder (3.2.2)
  * bundler (1.7.9)
  * crack (0.4.2)
  * domain_name (0.5.23)
  * equivalent-xml (0.5.1)
  * ffi (1.9.8)
  * haml (4.0.6)
  * http-cookie (1.0.2)
  * link_header (0.0.8)
  * linkeddata (1.1.2 85dfa93)
  * listen (2.10.0)
  * lumberjack (1.0.9)
  * method_source (0.8.2)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * net-http-persistent (2.9.4)
  * netrc (0.10.3)
  * nokogiri (1.6.6.2)
  * notiffany (0.0.6)
  * pry (0.10.1)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * rdf (1.1.10)
  * rdf-rdfxml (1.1.3 d3422f2)
  * rest-client (1.8.0)
  * rest-client-components (1.3.0)
  * safe_yaml (1.0.4)
  * shellany (0.0.1)
  * slop (3.6.0)
  * thor (0.19.1)
  * tilt (2.0.1)
  * unf (0.1.4)
  * unf_ext (0.0.6)

ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

**Comment by gkellogg** [comment]
See https://github.com/crohr/rest-client-components/pull/9 for a fix to rest-client-components.
